import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Your user ID (same as migration script)
const userId = "cmqtu1wie0000zd29f1k64me4";

// Paste your JSON here or import it
const productList: string[] = [
  "4-Korn Oats",
  "Apple",
  "Applestrudel",
  "Asian pear",
  "Avocado",
  "Avocado Bio",
  "Ayran",
  "Baby Spinach",
  "Baby cabbage",
  "Baby spinach",
  "Badam",
  "Banana",
  "Banana chips",
  "Basmati Rice",
  "Beans",
  "Beetroot",
  "Berries mix frozen",
  "Berry fronzen",
  "Berry mix",
  "Besan",
  "Bio Natur mild",
  "Bio natur",
  "Black eyed beans",
  "Blackberry",
  "Blatterteig",
  "Blueberry",
  "Bottle gourd",
  "Bread",
  "Bread powder",
  "Brinjal",
  "Broccoli",
  "Brocoli and Caulflower",
  "Brown chickpeas",
  "Burger bun",
  "Butter",
  "Butter Croissant",
  "Butter bio",
  "Butter paper",
  "Cabbage pickle",
  "Capsicum Mix",
  "Capsicum mix",
  "Capsicum red",
  "Carrot",
  "Carrot bio",
  "Cashew nut",
  "Cashew nuts",
  "Cauliflower",
  "Cheese",
  "Cheese cake",
  "Cheese gouda",
  "Cheese natur",
  "Cheese pasta",
  "Cherry",
  "Chia seed",
  "Chicken",
  "Chickpeas",
  "Chilli",
  "Chilli big",
  "Chilli powder",
  "Cinnamon",
  "Clementinen",
  "Coconut chips",
  "Coconut milk",
  "Coconut oil",
  "Coconut powder",
  "Coconut sugar",
  "Coconut water",
  "Coffee powder",
  "Condensed milk",
  "Coriander",
  "Coriander powder",
  "Corn",
  "Corn flour",
  "Coscos",
  "Couscous",
  "Cranberry",
  "Croissant Nuss",
  "Crushed chilli",
  "Cuccumber",
  "Cucumber",
  "Curry leaves",
  "Dates",
  "Dosa batter",
  "Dosa mix",
  "Dried chilli",
  "Easy palappam mix",
  "Egg",
  "Eggplant",
  "Falafel mix",
  "Fig",
  "Flake rice",
  "Flammkuchen",
  "French fries",
  "Fresh Milk 3.5%",
  "Fresh cheese",
  "Fresh cream",
  "Fried onion",
  "Garam masala",
  "Garlic",
  "Garlic powder",
  "Ginger",
  "Ginger Bio",
  "Ginger powder",
  "Glass noodles",
  "Grapefruit",
  "Grapes",
  "Grapes mix",
  "Grated coconut",
  "Greek yogurt",
  "Green dal",
  "Green gram",
  "Green peas",
  "Haselnut",
  "Honey",
  "Ice cream",
  "Jackfruit",
  "Jaggery",
  "Japanese Noodles",
  "Jasmine Rice",
  "Juice",
  "Kaki fruit",
  "Kiwi",
  "Lemon",
  "Lentil",
  "Lettuce",
  "Like Beef strips",
  "Like Doner",
  "Like chicken",
  "Lime pickle",
  "Maida roll",
  "Mandarin",
  "Mango",
  "Masala Peanut",
  "Melon",
  "Milk",
  "Milk 3.5%",
  "Milk 3.5% Milbona",
  "Milk 3.5% milsani",
  "Milk Bio",
  "Milk Rice",
  "Milk by Ja",
  "Milk rice",
  "Mint",
  "Mint leaves",
  "Mish6",
  "Mozarella cheese",
  "Mozzarella cheese",
  "Mushroom",
  "Musili",
  "Musk Melon",
  "Mustard seeds",
  "Natur",
  "Nut cream spread",
  "Nut mix",
  "Oats",
  "Oats Bio",
  "Olive",
  "Olive oil",
  "Onion",
  "Onion Bio",
  "Onion Red",
  "Onion Red Bio",
  "Onion red",
  "Orange",
  "Oregano",
  "Paneer",
  "Pappadanlm",
  "Paratha",
  "Pasta",
  "Pasta Wheat",
  "Pasta sauce",
  "Peanut",
  "Peanut roasted",
  "Pear",
  "Pepper powder",
  "Pizza sauce",
  "Pomegranate",
  "Ponni rice",
  "Porree",
  "Potato",
  "Pumkin seed",
  "Pumpkin",
  "Pumpkin seed",
  "Puttu podi",
  "Quark 40%",
  "Quinoa",
  "Radish",
  "Ragi",
  "Raisin",
  "Rava",
  "Raw rice",
  "Red Rice",
  "Red kidney beans",
  "Red lentil",
  "Rice Parboiled",
  "Rice basmati",
  "Rice brown",
  "Rice flakes",
  "Rice flour",
  "Rice noodles",
  "Rice paper",
  "Rice parboiled",
  "Rice parboiled Ja",
  "Roasted chana unsalted",
  "Salad mix",
  "Salt",
  "Salted Chickpeas",
  "Salted Peanut By Ja",
  "Seasamee ring",
  "Seed mix",
  "Semolina",
  "Sesame seed",
  "Snack",
  "Snack bread",
  "Snacks",
  "Snacks Couricini",
  "Snacks bread",
  "Soya chunks",
  "Soya milk",
  "Soya sauce",
  "Spaghetti",
  "Spinach",
  "Spinach Frozen",
  "Spinach frozen",
  "Spring onion",
  "Spring onion powder",
  "Sprouts",
  "Strawberry",
  "Strawberry fronzen",
  "Strudelteig",
  "Sugar powder",
  "Sunflower seed",
  "Sweet corn",
  "Sweet potato",
  "Tapioca powder",
  "Tea bag",
  "Tea powder",
  "Tofu",
  "Toilet paper",
  "Tomato",
  "Tomato sauce",
  "Tortilla wraps",
  "Tortillas wrap vollkorn",
  "Turmeric powder",
  "Urid dal",
  "Uzhunnu",
  "Vannilla essense",
  "Vinegar",
  "Vitamin juice",
  "Waffle",
  "Walnut",
  "Water melon",
  "Wheat powder",
  "Wheat powder 1050",
  "Wheat powder 550",
  "Wheat powder 630",
  "Wheat powder vollkorn",
  "Yogurt",
  "Yogurt Bio",
  "Yogurt Ja",
  "Yogurt by Ja",
  "Yogurt mild",
  "Zuckererbsen",
];

// normalize helper (VERY important for duplicates like case/spacing)
function normalizeName(name: string) {
  return name.trim().replace(/\s+/g, " ");
}

async function main() {
  console.log("🚀 Seeding products...");

  // remove duplicates (case-insensitive safe)
  const unique = new Map<string, string>();

  for (const name of productList) {
    const key = normalizeName(name).toLowerCase();

    if (!unique.has(key)) {
      unique.set(key, normalizeName(name));
    }
  }

  console.log(`📦 Unique products: ${unique.size}`);

  let count = 0;

  for (const name of unique.values()) {
    await prisma.product.create({
      data: {
        name,
        brandName: "",
        userId,
      },
    });

    count++;
  }

  console.log(`✅ Inserted ${count} products successfully`);
}

main()
  .catch((e) => {
    console.error("❌ Error seeding products:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
